apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.coinbetter.service: coinbtr-docs
  name: docs
spec:
  ports:
  - name: "4567"
    port: 4567
    targetPort: 4567
  selector:
    io.coinbetter.service: coinbtr-docs
  type: ClusterIP
status:
  loadBalancer: {}
